import { useNavigate, Link } from "react-router-dom";
import { useState } from 'react';
import { Activity, Menu, Globe, FileText, Download, Calendar, Filter, FileBarChart, Users, Stethoscope } from 'lucide-react';
import { BarChart, Bar, XAxis, YAxis, CartesianGrid, Tooltip as RechartsTooltip, ResponsiveContainer, Legend } from 'recharts';

const reportsData = [
  { name: 'Jan', hematology: 400, biochemistry: 240, microbiology: 120 },
  { name: 'Feb', hematology: 300, biochemistry: 139, microbiology: 220 },
  { name: 'Mar', hematology: 500, biochemistry: 380, microbiology: 180 },
  { name: 'Apr', hematology: 278, biochemistry: 390, microbiology: 200 },
  { name: 'May', hematology: 689, biochemistry: 480, microbiology: 218 },
  { name: 'Jun', hematology: 839, biochemistry: 380, microbiology: 250 },
];

const recentReports = [
  { id: 'REP-091', type: 'Monthly Aggregate', generatedBy: 'Dr. Sarah Jenkins', date: '2025-10-01', size: '2.4 MB' },
  { id: 'REP-092', type: 'Financial Summary', generatedBy: 'Admin', date: '2025-10-02', size: '1.1 MB' },
  { id: 'REP-093', type: 'Test Turnaround Time', generatedBy: 'System Auto', date: '2025-10-03', size: '3.5 MB' },
  { id: 'REP-094', type: 'Critical Results Log', generatedBy: 'Dr. Ahmad Khan', date: '2025-10-04', size: '845 KB' },
];

export default function ReportsScreen() {
  const [lang, setLang] = useState<'en' | 'ar'>('en');
  const navigate = useNavigate();
  const [sidebarOpen, setSidebarOpen] = useState(false);

  const t = {
    en: {
      title: "Analytical Reports",
      subtitle: "Generate, view, and export comprehensive laboratory performance and clinical data.",
      generateBtn: "Generate New Report",
      exportBtn: "Export Data",
      dateRange: "Last 6 Months",
      filter: "Filter",
      chartTitle: "Tests Volume by Category",
      catHem: "Hematology",
      catBio: "Biochemistry",
      catMicro: "Microbiology",
      recentTitle: "Generated Reports Archive",
      colId: "Report ID",
      colType: "Report Type",
      colGen: "Generated By",
      colDate: "Date",
      colSize: "Size",
      colAction: "Download"
    },
    ar: {
      title: "التقارير التحليلية",
      subtitle: "إنشاء وعرض وتصدير الأداء الشامل للمختبر والبيانات السريرية.",
      generateBtn: "إنشاء تقرير جديد",
      exportBtn: "تصدير البيانات",
      dateRange: "آخر 6 أشهر",
      filter: "تصفية",
      chartTitle: "حجم الاختبارات حسب الفئة",
      catHem: "أمراض الدم",
      catBio: "الكيمياء الحيوية",
      catMicro: "علم الأحياء الدقيقة",
      recentTitle: "أرشيف التقارير المنشأة",
      colId: "رقم التقرير",
      colType: "نوع التقرير",
      colGen: "بواسطة",
      colDate: "التاريخ",
      colSize: "الحجم",
      colAction: "تحميل"
    }
  };

  const isRtl = lang === 'ar';
  const currT = t[lang];

  return (
    <div dir={isRtl ? 'rtl' : 'ltr'} className="min-h-screen bg-background flex">
      {/* Sidebar - Desktop & Mobile overlay */}
      <aside className={`fixed inset-y-0 ${isRtl ? 'right-0' : 'left-0'} z-50 w-64 bg-surface border-${isRtl ? 'l' : 'r'} border-gray-200 transform transition-transform duration-300 ease-in-out md:translate-x-0 ${sidebarOpen ? 'translate-x-0' : (isRtl ? 'translate-x-full' : '-translate-x-full')} md:relative`}>
        <div className="flex items-center justify-between p-4 border-b border-gray-200">
          <div className="flex items-center gap-2 text-primary font-bold text-xl">
            <Activity className="w-6 h-6" />
            <span>SmartLab</span>
          </div>
          <button className="md:hidden p-1 text-gray-500" onClick={() => setSidebarOpen(false)}>
            &times;
          </button>
        </div>
        <nav className="p-4 space-y-2 flex-1">
          <Link to="/dashboard" className={`flex items-center gap-3 px-4 py-3 rounded-md font-medium transition-colors ${window.location.pathname === '/dashboard' ? 'bg-primary/10 text-primary border-l-4 border-primary' : 'text-gray-600 hover:bg-gray-50'}`}>
            <Activity className="w-5 h-5" />
            {lang === 'en' ? 'Dashboard' : 'لوحة القيادة'}
          </Link>
          <Link to="/patients" className={`flex items-center gap-3 px-4 py-3 rounded-md font-medium transition-colors ${window.location.pathname.startsWith('/patients') ? 'bg-primary/10 text-primary border-l-4 border-primary' : 'text-gray-600 hover:bg-gray-50'}`}>
            <Users className="w-5 h-5" />
            {lang === 'en' ? 'Patients' : 'المرضى'}
          </Link>
          <Link to="/tests" className={`flex items-center gap-3 px-4 py-3 rounded-md font-medium transition-colors ${window.location.pathname.startsWith('/tests') ? 'bg-primary/10 text-primary border-l-4 border-primary' : 'text-gray-600 hover:bg-gray-50'}`}>
            <Stethoscope className="w-5 h-5" />
            {lang === 'en' ? 'Medical Tests' : 'الاختبارات الطبية'}
          </Link>
          <Link to="/reports" className={`flex items-center gap-3 px-4 py-3 rounded-md font-medium transition-colors ${window.location.pathname === '/reports' ? 'bg-primary/10 text-primary border-l-4 border-primary' : 'text-gray-600 hover:bg-gray-50'}`}>
            <FileText className="w-5 h-5" />
            {lang === 'en' ? 'Reports' : 'التقارير'}
          </Link>
        </nav>
      </aside>

      {/* Main Content */}
      <main className="flex-1 flex flex-col min-w-0 h-screen overflow-hidden">
        <header className="bg-surface border-b border-gray-200 h-16 flex items-center justify-between px-4 md:px-8 shrink-0">
          <div className="flex items-center gap-4">
            <button className="md:hidden p-2 text-gray-500 -ml-2" onClick={() => setSidebarOpen(true)}>
              <Menu className="w-6 h-6" />
            </button>
            <h1 className="text-xl font-bold text-navy hidden sm:block">{currT.title}</h1>
          </div>
          <div className="flex-1 flex justify-end">
            <button 
              onClick={() => setLang(lang === 'en' ? 'ar' : 'en')}
              className="flex items-center gap-2 px-3 py-1.5 rounded-md text-sm font-medium text-gray-600 hover:bg-gray-100 transition-colors"
            >
              <Globe className="w-4 h-4" />
              {lang === 'en' ? 'العربية' : 'English'}
            </button>
          </div>
        </header>

        <div className="p-4 md:p-8 flex-1 overflow-y-auto">
          
          <div className="max-w-6xl mx-auto space-y-8">
            
            {/* Page Header */}
            <div className="flex flex-col md:flex-row md:items-end justify-between gap-4">
              <div>
                <h2 className="text-2xl font-bold text-navy mb-1">{currT.title}</h2>
                <p className="text-gray-500 text-sm">{currT.subtitle}</p>
              </div>
              <div className="flex items-center gap-3">
                <button className="flex items-center justify-center gap-2 px-4 py-2 border border-gray-300 rounded-md text-sm font-medium text-gray-700 hover:bg-gray-50 bg-white transition-colors">
                  <Download className="w-4 h-4" />
                  {currT.exportBtn}
                </button>
                <button className="flex items-center justify-center gap-2 bg-primary hover:bg-primary-hover text-white px-4 py-2 rounded-md text-sm font-medium transition-colors">
                  <FileBarChart className="w-4 h-4" />
                  {currT.generateBtn}
                </button>
              </div>
            </div>

            {/* Chart Section */}
            <div className="bg-surface border border-gray-200 rounded-lg shadow-sm p-6">
              <div className="flex flex-col sm:flex-row sm:items-center justify-between mb-6 gap-4">
                <h3 className="text-lg font-bold text-navy">{currT.chartTitle}</h3>
                <div className="flex items-center gap-2">
                  <button className="flex items-center gap-2 px-3 py-1.5 border border-gray-200 rounded-md text-sm font-medium text-gray-600 hover:bg-gray-50">
                    <Calendar className="w-4 h-4" />
                    {currT.dateRange}
                  </button>
                  <button className="flex items-center gap-2 px-3 py-1.5 border border-gray-200 rounded-md text-sm font-medium text-gray-600 hover:bg-gray-50">
                    <Filter className="w-4 h-4" />
                    {currT.filter}
                  </button>
                </div>
              </div>
              
              <div className="h-80 w-full">
                <ResponsiveContainer width="100%" height="100%">
                  <BarChart data={reportsData} margin={{ top: 20, right: 30, left: 0, bottom: 5 }}>
                    <CartesianGrid strokeDasharray="3 3" vertical={false} stroke="#E5E7EB" />
                    <XAxis dataKey="name" axisLine={false} tickLine={false} tick={{fill: '#6B7280', fontSize: 12}} />
                    <YAxis axisLine={false} tickLine={false} tick={{fill: '#6B7280', fontSize: 12}} />
                    <RechartsTooltip cursor={{fill: '#F3F4F6'}} contentStyle={{ borderRadius: '8px', border: 'none', boxShadow: '0 4px 6px -1px rgb(0 0 0 / 0.1)' }} />
                    <Legend iconType="circle" wrapperStyle={{ paddingTop: '20px' }} />
                    <Bar dataKey="hematology" name={currT.catHem} stackId="a" fill="#0052CC" radius={[0, 0, 0, 0]} />
                    <Bar dataKey="biochemistry" name={currT.catBio} stackId="a" fill="#00A3BF" radius={[0, 0, 0, 0]} />
                    <Bar dataKey="microbiology" name={currT.catMicro} stackId="a" fill="#0F9D58" radius={[4, 4, 0, 0]} />
                  </BarChart>
                </ResponsiveContainer>
              </div>
            </div>

            {/* Reports Archive Table */}
            <div className="bg-surface border border-gray-200 rounded-lg shadow-sm overflow-hidden">
              <div className="px-6 py-4 border-b border-gray-100 flex items-center justify-between">
                <h3 className="text-base font-bold text-navy">{currT.recentTitle}</h3>
              </div>
              <div className="overflow-x-auto">
                <table className="w-full text-left text-sm text-gray-600">
                  <thead className="bg-gray-50 text-xs uppercase text-gray-500 border-b border-gray-200">
                    <tr>
                      <th className="px-6 py-3 font-semibold">{currT.colId}</th>
                      <th className="px-6 py-3 font-semibold">{currT.colType}</th>
                      <th className="px-6 py-3 font-semibold">{currT.colGen}</th>
                      <th className="px-6 py-3 font-semibold">{currT.colDate}</th>
                      <th className="px-6 py-3 font-semibold">{currT.colSize}</th>
                      <th className="px-6 py-3 font-semibold text-center">{currT.colAction}</th>
                    </tr>
                  </thead>
                  <tbody className="divide-y divide-gray-100">
                    {recentReports.map((report) => (
                      <tr key={report.id} className="hover:bg-gray-50/50 transition-colors">
                        <td className="px-6 py-4 font-medium text-navy">{report.id}</td>
                        <td className="px-6 py-4 flex items-center gap-2">
                          <FileText className="w-4 h-4 text-primary" />
                          <span className="font-semibold text-gray-700">{report.type}</span>
                        </td>
                        <td className="px-6 py-4">{report.generatedBy}</td>
                        <td className="px-6 py-4">{report.date}</td>
                        <td className="px-6 py-4 text-gray-500 text-xs font-mono">{report.size}</td>
                        <td className="px-6 py-4 text-center">
                          <button className="text-primary hover:text-primary-hover hover:bg-primary/10 p-1.5 rounded-md transition-colors inline-flex">
                            <Download className="w-4 h-4" />
                          </button>
                        </td>
                      </tr>
                    ))}
                  </tbody>
                </table>
              </div>
            </div>

          </div>
        </div>
      </main>
    </div>
  );
}